# Generated by Django 4.2.7 on 2023-12-26 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=200)),
                ('LastName', models.CharField(max_length=200)),
                ('Gender', models.CharField(choices=[('Male', 'male'), ('Female', 'female')], max_length=200)),
                ('Phoneno', models.BigIntegerField()),
                ('age', models.IntegerField(max_length=200)),
            ],
        ),
    ]
