# Generated by Django 4.2.7 on 2023-12-26 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stuapp', '0004_alter_student_age'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student',
            table='stuinfo',
        ),
    ]
